#!/bin/bash

echo "=== TESTING HALLOWEEN MODE ==="
echo ""
echo "1. Testing normal mode (arena):"
echo "   Should use images-5.jpeg and images-6.jpeg for walls"
echo "   Run: ./arena"
echo ""
echo "2. Testing Halloween mode (arena):"
echo "   Should use hallowen1.jpg for walls AND hallowenpisos.png for floor"
echo "   Run: ./arena --halloween"
echo ""
echo "3. Testing normal mode (arena2):"
echo "   Should use glass1.jpg and glass2.jpeg for walls"  
echo "   Run: ./arena2"
echo ""
echo "4. Testing Halloween mode (arena2):"
echo "   Should use hallowen2.jpeg for walls"
echo "   Run: ./arena2 --halloween"
echo ""
echo "=== FILES READY ==="
ls -la arena arena2 2>/dev/null || echo "ERROR: Binaries not found. Run 'make arena arena2' first."
echo ""
echo "=== HALLOWEEN ASSETS ==="
ls -la sources/hallowen*.jpg sources/hallowen*.jpeg sources/hallowenpisos.png 2>/dev/null || echo "ERROR: Halloween assets not found"
echo ""
echo "Press any key to test arena with Halloween mode..."
read -n 1
./arena --halloween